# Site settings
title: KNOSSOS &mdash; 3D image data visualization and annotation
name: KNOSSOS
email: knossos-team@mpimf-heidelberg.mpg.de
description: > # this means to ignore newlines until "baseurl:"
  Knossos is a scientific application for 3D image data skeletonization.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://knossostool.org" # the base hostname & protocol for your site
github_username:  knossos-project

# Build settings
markdown: kramdown
