# Site settings
title: KNOSSOS &mdash; 3D image annotation
name: KNOSSOS
email: knossos-team@mpimf-heidelberg.mpg.de
description: > # this means to ignore newlines until "baseurl:"
  Knossos is a scientific application for 3D image data skeletonization.
baseurl: "/knossos" # the subpath of your site, e.g. /blog/
url: "http://www.knossostool.org" # the base hostname & protocol for your site
github_username: knossos-project

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true
  # auto_ids: false

sass:
  style: :compressed

exclude:
  - "bower_components"
  - "bower.json"
  - "feed.xml"
  - "Makefile"
